# Generated by Django 3.2.12 on 2022-04-01 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expensesystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='expense',
            table='Expense',
        ),
    ]
