# Generated by Django 3.2.12 on 2022-04-01 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensesystem', '0002_alter_expense_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='userId',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.CharField(max_length=42, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
