# Generated by Django 3.2.12 on 2022-04-06 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expensesystem', '0005_auto_20220406_2051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='us',
            new_name='owner',
        ),
    ]
