# Generated by Django 3.2.12 on 2022-04-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensesystem', '0007_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
    ]
