# Generated by Django 3.2.12 on 2022-04-20 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expensesystem', '0011_auto_20220415_2307'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
