# Generated by Django 3.2.12 on 2022-04-24 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expensesystem', '0015_auto_20220424_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
    ]
