# Generated by Django 3.2.12 on 2022-04-24 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensesystem', '0016_auto_20220425_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
